# Copyright (c) K-Society and contributors. All rights reserved. Licensed under the Microsoft Reciprocal License. See LICENSE.TXT file in the project root for full license information.
#

branches:
  only:
    - master
    - develop

image: Visual Studio 2019

version: 0.0.0.{build}
platform: Any CPU
configuration: Release

environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  NUGET_XMLDOC_MODE: skip
  InstallSystemVersion: 0.0.0.0
  
install:
  - echo Downlaod Erlang otp
  - ps: New-Item -ItemType Directory -Path ".\Src\KSociety.RabbitMQ.Install\Files\x32"
  - ps: New-Item -ItemType Directory -Path ".\Src\KSociety.RabbitMQ.Install\Files\x64"
  - ps: Invoke-WebRequest -Uri "https://github.com/erlang/otp/releases/download/OTP-23.2.5/otp_win32_23.2.5.exe" -OutFile ".\Src\KSociety.RabbitMQ.Install\Files\x32\otp_win32_23.2.5.exe"
  - ps: Invoke-WebRequest -Uri "https://github.com/erlang/otp/releases/download/OTP-23.2.5/otp_win64_23.2.5.exe" -OutFile ".\Src\KSociety.RabbitMQ.Install\Files\x64\otp_win64_23.2.5.exe"
  
build:
  verbosity: minimal #quiet|minimal|normal|detailed

build_script:
  - appveyor.cmd
  
after_build:
 - ps: $installSystemPath = Resolve-Path .\Src\00\KSociety.RabbitMQ.Install\RabbitMQSystem.exe; $array = [System.Diagnostics.FileVersionInfo]::GetVersionInfo("$installSystemPath").FileVersion -split "\."; $env:InstallSystemVersion = $array[0] + "." + $array[1] + "." + $array[2]; Write-Host "$env:InstallSystemVersion"

test: off

pull_requests:
  do_not_increment_build_number: true

nuget:
  disable_publish_on_pr: true

skip_branch_with_pr: true
skip_tags: true

artifacts:
  - path: build\**\Release\*.nupkg
    name: nuget
  - path: Src\00\KSociety.RabbitMQ.Install\RabbitMQSystem.exe
    name: rabbitmqsysteminstaller

deploy:
  - provider: GitHub
    release: RabbitMQSystem $(InstallSystemVersion)
    description: 'RabbitMQSystem $(InstallSystemVersion)'
    auth_token:
      secure: 7XvMBiUsnXWGCogi909uIzQVH/68TW4lAipl0RN+ZAwHrlqZChxEBroMRWEcrWGM
    artifact: rabbitmqsysteminstaller
    draft: false
    prerelease: false
    force_update: true
    tag: $(InstallSystemVersion)
    on:
      branch: master
      #appveyor_repo_tag: true

